### ISSUE TITLE
I'm dumb

### ISSUE THREAD

**Issue by cardonasMind** [lucidrains/PaLM-rlhf-pytorch#11]
Hey is a web to interact with model, or how much does it cost to train model in my own computer? I play Valorant with low graphics so is not best as you can imagine

**Comment by lucidrains** [comment]
in short, you won't be able to do it, not alone

**Comment by lucidrains** [comment]
however, the repository will be great as a base for academics doing small scale research. the technique is very general. you can imagine adapting to say [protein design](https://arxiv.org/abs/2004.03497)
