### ISSUE TITLE
Is it possible to release a code based on jax?

### ISSUE THREAD

**Issue by sglucas** [lucidrains/PaLM-rlhf-pytorch#16]
Is it possible to release a code based on jax?

**Comment by lucidrains** [comment]
hmm, which organization are you a part of? or you are on the TRC program?

**Comment by sglucas** [comment]
@lucidrains Hi, I'm supported by TRC program and I can use TPUs to do some research. 

Thank you very much for your contribution.

**Comment by lucidrains** [comment]
@sglucas once the dust settles, i'll see what i can do, probably using the [equinox library](https://github.com/patrick-kidger/equinox)

**Comment by conceptofmind** [comment]
@lucidrains @sglucas 

I will begin to work on a release in Jax now. Will follow the same exact structure as the PyTorch version: https://github.com/conceptofmind/PaLM-rlhf-jax

Is there a preference in a framework? I can either do Flax or Haiku.

**Comment by lucidrains** [comment]
> @lucidrains @sglucas
> 
> I will begin to work on a release in Jax now. Will follow the same exact structure as the PyTorch version: https://github.com/conceptofmind/PaLM-rlhf-jax
> 
> Is there a preference in a framework? I can either do Flax or Haiku. Flax is more well-maintained and Cristian / Marc are likely to answer questions in the discussion threads but if there is a strong preference for Haiku that can be done as well.

flax would be the safe bet, but i'm also a fan of Patrick Kidger's [Equinox](https://github.com/patrick-kidger/equinox)

**Comment by lucidrains** [comment]
> @lucidrains @sglucas
> 
> I will begin to work on a release in Jax now. Will follow the same exact structure as the PyTorch version: https://github.com/conceptofmind/PaLM-rlhf-jax
> 
> Is there a preference in a framework? I can either do Flax or Haiku. Flax is more well-maintained and Cristian / Marc are likely to answer questions in the discussion threads but if there is a strong preference for Haiku that can be done as well.

flax would be the safe bet, but i'm also a fan of Patrick Kidger's [Equinox](https://github.com/patrick-kidger/equinox) . i'll let you and @sglucas decide!

**Comment by conceptofmind** [comment]
Got accepted to the TRC program this morning as well. Going to go with the safe bet in Flax to start. Can convert to other frameworks later. I will let you know when it is finished by either adding to here or email.

Thank you,

Enrico

**Comment by yejingxin** [comment]
Hi Enrico,

Is there new update on this recently? 

Have you got your TPU you need? If not, we (from CloudTPU) can provide more help on this.

Thanks,
Jingxin

**Comment by conceptofmind** [comment]
> Hi Enrico,
> 
> Is there new update on this recently?
> 
> Have you got your TPU you need? If not, we (from CloudTPU) can provide more help on this.
> 
> Thanks, Jingxin

Hi Jingxin,

I have been working on this locally. I have not pushed the updates to Github yet as the TRC program only gives limited access to TPUs so I have to be cautious with my use.

If you are able to provide access to TPU time for testing that would be greatly appreciated. 

I will try to push more updates soon.

Thank you,

Enrico
