### ISSUE TITLE
Are there some pictures that describe PaLM architecture?

### ISSUE THREAD

**Issue by guotong1988** [lucidrains/PaLM-rlhf-pytorch#29]
Thank you very much!

**Comment by lucidrains** [comment]
![Screenshot from 2023-02-14 09-59-23](https://user-images.githubusercontent.com/108653/218819536-ca505be5-f8c6-4fc0-a04e-b7ce07f92bd0.png)

yea sure, they actually used it for vision recently with great results https://arxiv.org/pdf/2302.05442.pdf
