### ISSUE TITLE
speed up with flash attn in A6000?

### ISSUE THREAD

**Issue by wac81** [lucidrains/PaLM-rlhf-pytorch#47]
please check it.
https://www.reddit.com/r/StableDiffusion/comments/xmr3ic/speed_up_stable_diffusion_by_50_using_flash/

but it's not speed up  use palm model with flash attn param in A6000 in my case.

**Comment by conceptofmind** [comment]
PyTorch 2.0 Flash Attention requires a SM80 architecture. The A6000 has a SM86 architecture. It is not currently supported. And just to clarify again, you can not use a `dim_head` above 128.

**Comment by wac81** [comment]
> PyTorch 2.0 Flash Attention requires a SM80 architecture. The A6000 has a SM86 architecture. It is not currently supported. And just to clarify again, you can not use a `dim_head` above 128.

thank you a lot
